color0 #3a4857
color1 #ffb4ab
color2 #4cdadd
color3 #80d4d6
color4 #9ccbfb
color5 #4cdadd
color6 #80d4d6
color7 #dce3ee
color8 #8492a3
color9 #ffb4ab
color10 #4cdadd
color11 #80d4d6
color12 #9ccbfb
color13 #4cdadd
color14 #80d4d6
color15 #dce3ee

cursor                #dce3ee
cursor_text_color     #0d141b
background            #0d141b
foreground            #dce3ee
selection_foreground  #b9c8da
selection_background  #3a4857
active_border_color   #4cdadd
inactive_border_color #3a4857
url_color             #4cdadd

active_tab_foreground   #003738
active_tab_background   #4cdadd
inactive_tab_foreground #b9c8da
inactive_tab_background #3a4857
cursor_trail_color      #b9c8da
