color0 #484459
color1 #ffb4ab
color2 #8ecdff
color3 #97ccf8
color4 #c9beff
color5 #8ecdff
color6 #97ccf8
color7 #e6e0ef
color8 #938ea5
color9 #ffb4ab
color10 #8ecdff
color11 #97ccf8
color12 #c9beff
color13 #8ecdff
color14 #97ccf8
color15 #e6e0ef

cursor                #e6e0ef
cursor_text_color     #14121c
background            #14121c
foreground            #e6e0ef
selection_foreground  #c9c3dc
selection_background  #484459
active_border_color   #8ecdff
inactive_border_color #484459
url_color             #8ecdff

active_tab_foreground   #00344f
active_tab_background   #8ecdff
inactive_tab_foreground #c9c3dc
inactive_tab_background #484459
cursor_trail_color      #c9c3dc
