color0 #3b4858
color1 #ffb4ab
color2 #4cd9e2
color3 #80d4da
color4 #9fcafd
color5 #4cd9e2
color6 #80d4da
color7 #dde3ee
color8 #8592a4
color9 #ffb4ab
color10 #4cd9e2
color11 #80d4da
color12 #9fcafd
color13 #4cd9e2
color14 #80d4da
color15 #dde3ee

cursor                #dde3ee
cursor_text_color     #0d141c
background            #0d141c
foreground            #dde3ee
selection_foreground  #bac8db
selection_background  #3b4858
active_border_color   #4cd9e2
inactive_border_color #3b4858
url_color             #4cd9e2

active_tab_foreground   #00373a
active_tab_background   #4cd9e2
inactive_tab_foreground #bac8db
inactive_tab_background #3b4858
cursor_trail_color      #bac8db
